// generated by stringer -type=ServiceEventKind; DO NOT EDIT

package hooktest

import "fmt"

const _ServiceEventKind_name = "ServiceEventInstallServiceEventStartServiceEventErrorServiceEventStopServiceEventRemove"

var _ServiceEventKind_index = [...]uint8{0, 19, 36, 53, 69, 87}

func (i ServiceEventKind) String() string {
	i -= 1
	if i < 0 || i >= ServiceEventKind(len(_ServiceEventKind_index)-1) {
		return fmt.Sprintf("ServiceEventKind(%d)", i+1)
	}
	return _ServiceEventKind_name[_ServiceEventKind_index[i]:_ServiceEventKind_index[i+1]]
}
